// Generated by CoffeeScript 2.5.1
(function() {
  // TestCoffee.coffee - The test game, CoffeeScript version
  var $maxNumberDescription, Create, GetEventDescriptionColor, GetEventDescriptionText, GetEventDescriptionY, GetImageRotation, GetImageX, GetImageY, GetNumberEventText, GetSystemTimeText, OnFrame, Redraw, textCommon;

  Create = function() {
    console.log('[TestCoffee] create game');
    return {
      // initial states
      numberEvent: 0,
      numberSecond: 0,
      loggingEventList: []
    };
  };

  GetSystemTimeText = function(context) {
    return `System time: ${context.system.numberMillisecond.toFixed(2)}ms`;
  };

  GetNumberEventText = function(numberEvent) {
    return `Number of events: ${numberEvent}`;
  };

  // adjust movement period with canvas pixel size
  // so it will not move too fast/slow on large/small screen
  // introduce a 571:431 factor in period ratio so it looks like random moving
  GetImageX = function(t, w, h) {
    var t1;
    t1 = t / 1000 / ((w + h) / 571);
    return (Math.sin(t1 * (2 * Math.PI)) + 1) / 2;
  };

  GetImageY = function(t, w, h) {
    var t1;
    t1 = t / 1000 / ((w + h) / 431);
    return (Math.sin(t1 * (2 * Math.PI)) + 1) / 2;
  };

  GetImageRotation = function(t) {
    return t / 1023 * (2 * Math.PI);
  };

  GetEventDescriptionText = function(event) {
    switch (`${event.target}/${event.name}`) {
      case 'stage%%0/keydown':
        return `Keydown: key = ${event.value}`;
      case 'stage%%0/swipe':
        return `Swipe: direction = ${event.value}`;
      case 'image%coffee%0/click':
      case 'image%coffee%0/tap':
        return "Coffee is clicked/tapped";
    }
  };

  textCommon = {
    x: 0.0,
    fontSize: 0.03,
    fontFamily: 'Lato',
    fill: 'black'
  };

  $maxNumberDescription = 20;

  GetEventDescriptionY = function(eventIndex, numberEvent) {
    return 0.04 * 2 + (numberEvent - eventIndex - 1) * 0.04;
  };

  GetEventDescriptionColor = function(eventIndex, numberEvent) {
    var fadingLevel, gray, n;
    n = numberEvent - eventIndex;
    fadingLevel = n - $maxNumberDescription + 7;
    if (fadingLevel <= 0) {
      return 'black';
    }
    gray = 32 * fadingLevel;
    return `rgb(${gray}, ${gray}, ${gray})`;
  };

  Redraw = function(context, data) {
    var event, i, len, ref;
    console.log('[TextCoffee] redraw game');
    // no elegant way to remove parentheses after Create, what a pity for junkrat revision
    context.Create('stage%%0').Stage({
      eventList: ['keydown', 'swipe']
    });
    context.Create('text%system-time%0').Text({
      y: 0.0,
      text: GetSystemTimeText(context),
      ...textCommon
    });
    context.Create('text%number-event%0').Text({
      y: 0.04,
      text: GetNumberEventText(data.numberEvent),
      ...textCommon
    });
    ref = data.loggingEventList;
    for (i = 0, len = ref.length; i < len; i++) {
      event = ref[i];
      if (event.index < data.numberEvent - $maxNumberDescription) {
        continue;
      }
      context.Create(`text%event-description%${event.index}`).Text({
        y: GetEventDescriptionY(event.index, data.numberEvent),
        text: GetEventDescriptionText(event),
        ...textCommon
      });
    }
    context.Create('image%coffee%0').Image({
      url: 'Resource/Coffee.svg',
      x: GetImageX(context.system.numberMillisecond, context.system.width, context.system.height),
      y: GetImageY(context.system.numberMillisecond, context.system.width, context.system.height),
      rotation: GetImageRotation(context.system.numberMillisecond),
      width: 0.12 / context.system.aspectRatio,
      height: 0.1,
      crop: {
        width: 120,
        height: 100
      },
      eventList: ['click', 'tap']
    });
    return null;
  };

  OnFrame = function(context, data) {
    var event, eventList, i, j, len, len1, loggingEventList, name, numberEvent, ref, target, value;
    context.Update('text%system-time%0', {
      text: GetSystemTimeText(context)
    });
    context.Update('image%coffee%0', {
      x: GetImageX(context.system.numberMillisecond, context.system.width, context.system.height),
      y: GetImageY(context.system.numberMillisecond, context.system.width, context.system.height),
      rotation: GetImageRotation(context.system.numberMillisecond)
    });
    numberEvent = data.numberEvent;
    eventList = [];
    ref = [['stage%%0', 'keydown'], ['stage%%0', 'swipe'], ['image%coffee%0', 'click'], ['image%coffee%0', 'tap']];
    for (i = 0, len = ref.length; i < len; i++) {
      [target, name] = ref[i];
      while (value = context.DequeueEvent(target, name)) {
        eventList.push({
          index: numberEvent,
          target,
          name,
          value
        });
        numberEvent += 1;
      }
    }
    if (numberEvent !== data.numberEvent) {
      context.Update("text%number-event%0", {
        text: GetNumberEventText(numberEvent)
      });
    }
    loggingEventList = data.loggingEventList;
    for (j = 0, len1 = eventList.length; j < len1; j++) {
      event = eventList[j];
      context.Create(`text%event-description%${event.index}`).Text({
        y: GetEventDescriptionY(event.index, numberEvent),
        text: GetEventDescriptionText(event),
        ...textCommon
      });
      loggingEventList.push(event);
    }
    loggingEventList = loggingEventList.filter(function(event) {
      if (event.index < numberEvent - $maxNumberDescription) {
        context.Remove(`text%event-description%${event.index}`);
        return false;
      }
      context.Update(`text%event-description%${event.index}`, {
        y: GetEventDescriptionY(event.index, numberEvent),
        fill: GetEventDescriptionColor(event.index, numberEvent)
      });
      return true;
    });
    return {
      // updated states
      numberEvent: numberEvent,
      numberSecond: data.numberSecond,
      loggingEventList: loggingEventList
    };
  };

  application.RegisterGame({
    name: 'Test Coffee',
    description: 'A testing game written in CoffeeScript.',
    aspectRatio: null,
    featureTagList: ['shape:text', 'shape:image', 'event:keydown', 'event:click', 'event:swipe', 'event:tap'],
    contextRevision: 'junkrat',
    interface: {Create, Redraw, OnFrame}
  });

}).call(this);

//# sourceMappingURL=TestCoffee.js.map
